services:
    movie-script-database:
        image: ceramicwhite/movie-script-database
        container_name: movie-script-database
        restart: on-failure
        init: true
        environment:
            - RUN_GET_SCRIPTS=true
            - USE_IMSDB=true
            - USE_SCREENPLAYS=true
            - USE_SCRIPTSAVANT=true
            - USE_AWESOMEFILM=true
            - USE_SFY=true
            - USE_SCRIPTSLUG=true
            - USE_ACTORPOINT=true
            - USE_SCRIPTPDF=true
            - USE_DAILYSCRIPT=false # DailyScript is not working
            ##### Metadata #####
            - RUN_GET_METADATA=true
            - TMDB_API_KEY=your_api_key_here
        volumes:
            - ./data/logs:/app/logs
            - ./data/scripts:/app/scripts
            - ./data/metadata:/app/metadata